import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#E5E5E5',
    flex: 1,
    padding: 20,
    // alignItems: 'center',
    // justifyContent: 'space-between',
  },
  explore: {
    fontSize: 32,
    fontFamily: 'Gordita',
    fontWeight: '600',
    color: '#000000',
  },
  bestOutfit: {
    fontSize: 20,
    fontFamily: 'Gordita',
    fontWeight: '600',
    color: '#000000',
    opacity: 0.3,
    marginBottom: 50,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor: 'blue',
    height: '100%',
    width: '80%',
  },
  filterContainer: {
    marginBottom: 50,
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 5,
    borderRadius: 10,
    height: 60,
    width: '100%',
  },
  searchIcon: {
    marginLeft: 10,
    fontSize: 20,
    color: '#000000',
    opacity: 0.5,
    width: '10%',
    // backgroundColor: 'yellow',
  },
  searchInput: {
    marginLeft: 10,
    fontSize: 18,
    color: '#000000',
    opacity: 0.65,
    // backgroundColor: 'yellow',
    height: '100%',
    width: '80%',
    justifyContent: 'center',
  },
  filterButton: {
    backgroundColor: '#F67952',
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  clothesType: {
    marginBottom: 30,
  },
  typeButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.02)',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    width: 70,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
  },
  typeText: {
    fontFamily: 'Gordita',
    fontWeight: '500',
    fontSize: 12,
    color: '#000000',
    opacity: 0.5,
    marginTop: 5,
  },
  arrivalContainer: {
    marginBottom: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textArrival: {
    fontFamily: 'Gordita',
    fontWeight: '500',
    fontSize: 20,
    color: '#000000',
    letterSpacing: 1,
  },
  textSeeAll: {
    fontFamily: 'Gordita',
    fontWeight: '400',
    fontSize: 14,
    color: '#000000',
    opacity: 0.5,
  },
  arrivalList: {
    marginBottom: 50,
  },
});
