export const Images = {
  light_Stroke_1x: require('@/Images/Arrow/Light/Stroke1.png'),
  dark_Stroke_1x: require('@/Images/Arrow/Dark/Stroke1.png'),
  Onbroding1_pic: require('@/Images/Onbroding/Group.png'),
  Onbroding2_pic: require('@/Images/Onbroding2/Group265.png'),
  Onbroding3_pic: require('@/Images/Onbroding3/Group233.png'),
  LoginIcon: require('@/Images/Symbol/Vector.png'),
  email_Icon: require('@/Images/Email/Message.png'),
  password_Icon: require('@/Images/Password/Lock.png'),
  fb_icon: require('@/Images/Facebook/fb.png'),
  gg_icon: require('@/Images/Google/gg.png'),
  profile_1x: require('@/Images/Name/Profile.png'),
  check_1x: require('@/Images/Check/Tick.png'),
  avatar_1x: require('@/Images/Avatar/Avatar1x.png'),
  // avatar_2x: require('@/Images/Avatar/Avatar@2x.png'),
  avatar_3x: require('@/Images/Avatar/Avatar3x.png'),
  RightArrow_1x: require('@/Images/RightArrow/RightArrow1x.png'),
  // RightArrow_2x: require('@/Images/RightArrow/RightArrow@2x.png'),
  // RightArrow_3x: require('@/Images/RightArrow/RightArrow@3x.png'),
  Heart_1x: require('@/Images/Heart/Heart.png'),
  Wallet_1x: require('@/Images/Wallets/Wallet.png'),
  Order_1x: require('@/Images/Order/Bag.png'),
  Document_1x: require('@/Images/Document/Document.png'),
  Lock_1x: require('@/Images/Lock/Lock.png'),
  Setting_1x: require('@/Images/Settings/Setting.png'),
  Logout_1x: require('@/Images/Logout/Logout.png'),
  Notification_1x: require('@/Images/Notification/Notification.png'),
  Circle_1x: require('@/Images/Circle/Circle.png'),
  Drawer_1x: require('@/Images/Drawer/Drawer1x.png'),
  Filter_1x: require('@/Images/Filter/Filter.png'),
  Dress_1x: require('@/Images/Clothes/Dress/Dress.png'),
  Shirt_1x: require('@/Images/Clothes/Shirt/Shirt.png'),
  Pants_1x: require('@/Images/Clothes/Pants/Pants.png'),
  Tshirt_1x: require('@/Images/Clothes/Tshirt/Tshirt.png'),
  sample1: require('@/Images/Clothes/sample/1.png'),
  sample2: require('@/Images/Clothes/sample/2.png'),
  sample3: require('@/Images/Clothes/sample/3.png'),
  sample4: require('@/Images/Clothes/sample/4.png'),
  sample5: require('@/Images/Clothes/sample/5.png'),
  sample6: require('@/Images/Clothes/sample/6.png'),
  goback_1x: require('@/Images/GoBack/Goback_1x.png'),
  more_1x: require('@/Images/More/More_1x.png'),
  product_detail: require('@/Images/ProductDetails/1.png'),
  product_black: require('@/Images/ProductDetails/black.png'),
  product_white: require('@/Images/ProductDetails/white.png'),
  product_beige: require('@/Images/ProductDetails/beige.png'),
  product_red: require('@/Images/ProductDetails/red.png'),
  Splash_icon: require('@/Images/Splash/Vector.png'),
  ApplePay: require('@/Images/PaymentMethod/ApplePay/ApplePay.png'),
  MasterCard: require('@/Images/PaymentMethod/MasterCard/Mastercard.png'),
  Paypal: require('@/Images/PaymentMethod/Paypal/PayPal.png'),
  Visa: require('@/Images/PaymentMethod/VisaPay/visa.png'),
  Profile_background: require('@/Images/ProfileBackground/profile_background.png'),
  Statistics_order: require('@/Images/StatisticsIcon/Order/Bag.png'),
  Statistics_promocodes: require('@/Images/StatisticsIcon/Promocodes/Ticket.png'),
  Statistics_reviewes: require('@/Images/StatisticsIcon/Reviewes/star.png'),
};
