import {StyleSheet, Dimensions} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
export default StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E5E5E5',
    height: windowHeight,
  },
  image: {
    // width: 54,
    // height: 62,
  },
  titleStyle: {
    color: '#000000',
    fontSize: 22,
    fontWeight: '600',
    fontFamily: 'Gordita',
    marginTop: 20,
  },
  inputContainer: {
    flexDirection: 'row',
    marginVertical: 5,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    width: 335,
    height: 57,
    alignItems: 'center',
    padding: 10,
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 20},
    // shadowRadius: 20,
    shadowOpacity: 0.3,
    elevation: 5,
  },
  shadow: {
    backgroundColor: '#FFF',
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 10},
    // shadowRadius: 20,
    shadowOpacity: 1,
    elevation: 5,
    borderRadius: 10,
    shadowRadius: 10,
  },
  iconContainer: {
    width: 48,
    height: 45,
    backgroundColor: 'rgba(246, 121, 82, 0.1)',
    // backgroundColor: '#FFF',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    // shadowColor: '#000029',
    // shadowOffset: {width: 0, height: 10},
    // // shadowRadius: 20,
    // shadowOpacity: 0.5,
    // elevation: 5,
  },
  emailIcon: {
    width: 24,
    height: 24,
    // backgroundColor: 'red',
  },
  inputBox: {
    // backgroundColor: 'red',
    height: 57,
    width: 335 - 10 - 48,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    fontSize: 12,
    // opacity: 0.5,
    fontWeight: '400',
    marginLeft: 5,
    color: '#000000',
  },
  forgotPassword: {
    marginTop: 5,
    alignItems: 'flex-end',
    // backgroundColor: 'red',
    width: 335,
  },
  forgotPasswordText: {
    color: '#230A06',
    fontWeight: '400',
    fontSize: 12,
  },
  buttonStyle: {
    marginTop: 20,
    flexDirection: 'row',
    backgroundColor: '#F67952',
    width: 205,
    height: 59,
    borderRadius: 133,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    fontSize: 16,
    fontFamily: 'Gordita',
    fontWeight: '500',
    lineHeight: 18.72,
    color: '#FFFFFF',
  },
  otherMethod: {
    flexDirection: 'row',
    marginTop: 50,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  underLine: {
    borderBottomWidth: 1,
    width: 90,
    marginHorizontal: 15,
  },
  orStyle: {
    color: '#230A06',
    fontSize: 12,
  },
  methodContainer: {
    flexDirection: 'row',
    marginTop: 40,
  },
  fbBackground: {
    marginHorizontal: 20,
    width: 70,
    height: 70,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
  },
  fbStyle: {
    width: 32,
    height: 32,
  },
  noAccContainer: {
    flexDirection: 'row',
    marginTop: 60,
  },
  noAccText: {
    color: 'rgba(0, 0, 0, 0.5)',
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'Gordita',
  },
  signUpText: {
    color: '#000000',
    fontWeight: '600',
  },
});
